### ISSUE TITLE
GpSync unit uses GpThreads unit, which is not present on github

### ISSUE THREAD

**Issue by alan008** [gabr42/GpDelphiUnits#16]
See issue title

**Comment by alan008** [comment]
TNamedThread class implementation is missing

**Comment by alan008** [comment]
Any chance to see GpThreads.pas unit in this collection on github ?

**Comment by alan008** [comment]
Still need GpThreads.pas ;..((..

**Comment by gabr42** [comment]
I tried to fix it but it got really messay (GpThreads is full of non-public code) so I just reverted GpSync to the previous version.

**Comment by alan008** [comment]
Thanks, Primoz! This solution is acceptable. For me it was more important that all units in GpDelphiUnits and OTL are consistent.

**Comment by gabr42** [comment]
> Still need GpThreads.pas ;..((..
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.

Anton, hi, sorry it took so long.
 
It turns out that GpThreads is full of non-open source code and links into core of our company's stuff. I tried to separate it into public/company side but it got really messy. At the end I just reverted the GpSync commit so it is again based on TThread.
 
Primož
