### ISSUE TITLE
GpCommandLineParser.pas Delphi XE 1 compatibily

### ISSUE THREAD

**Issue by stbland** [gabr42/GpDelphiUnits#7]
GpCommandLineParser.pas isn't compatible with Delphi XE 1

I need to define unit aliases like :

System.SysUtils=SysUtils
System.StrUtils=StrUtils
System.Classes=Classes
System.Generics.Defaults=Generics.Defaults
System.Generics.Collections=Generics.Collections

And TIStringComparer interface doesn't exist

**Comment by gabr42** [comment]
Feel free to fix it to work with XE. I'll incorporate the changes.

**Comment by gabr42** [comment]
Feel free to fix it to work with XE. I'll incorporate the changes.

**Comment by gabr42** [comment]
Feel free to fix it to work with XE. I'll incorporate the changes.
